services:
  mongo:
    image: mongo:7
    container_name: tpc-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tpc_db
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: tpc-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
